<?php

use Illuminate\Database\Seeder;

class PredmetsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('predmets')->delete();
        DB::table('predmets')->insert($this->pred);
    }
    private $pred = array(
	array(
		"kratpred" => "TEHNO",
		"nazpred" => "Elektrotehnička tehnologija",
		"siforgjed" => 100003,
		"upisanostud" => 2,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "EEL",
		"nazpred" => "Energetska elektronika",
		"siforgjed" => 100005,
		"upisanostud" => 6,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "RASAKO",
		"nazpred" => "Radiorelejne i satelitske komunikacije",
		"siforgjed" => 100011,
		"upisanostud" => 6,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "ELAK",
		"nazpred" => "Elektroakustika",
		"siforgjed" => 100009,
		"upisanostud" => 0,
		"brojsatitjedno" => 4,
	),
	array(
		"kratpred" => "MUE",
		"nazpred" => "Mjerenja u elektrotehnici",
		"siforgjed" => 100003,
		"upisanostud" => 0,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ELTER",
		"nazpred" => "Elektrotermija",
		"siforgjed" => 100001,
		"upisanostud" => 1,
		"brojsatitjedno" => 1,
	),
	array(
		"kratpred" => "GOMUAK",
		"nazpred" => "Govorna i muzička akustika",
		"siforgjed" => 100009,
		"upisanostud" => 2,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "INSKEE",
		"nazpred" => "Integrirani sklopovi energetske elektronike",
		"siforgjed" => 100005,
		"upisanostud" => 6,
		"brojsatitjedno" => NULL,
	),
	array(
		"kratpred" => "KOELU",
		"nazpred" => "Komponente elektroničkih uređaja i mjerne metode",
		"siforgjed" => 100010,
		"upisanostud" => 3,
		"brojsatitjedno" => NULL,
	),
	array(
		"kratpred" => "KVELUR",
		"nazpred" => "Kvaliteta elektroakustičkih uređaja",
		"siforgjed" => 100009,
		"upisanostud" => 0,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "PORAK",
		"nazpred" => "Pokretne radiokomunikacije",
		"siforgjed" => 100011,
		"upisanostud" => 5,
		"brojsatitjedno" => 4,
	),
	array(
		"kratpred" => "PRAPO",
		"nazpred" => "Projektiranje radiofrekvencijskih pojačala",
		"siforgjed" => 100011,
		"upisanostud" => 2,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "PROAK",
		"nazpred" => "Prostorna akustika",
		"siforgjed" => 100009,
		"upisanostud" => 0,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ULHID",
		"nazpred" => "Ultrazvuk i hidroakustika",
		"siforgjed" => 100009,
		"upisanostud" => 70,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "EKELS",
		"nazpred" => "Ekonomika elektroničkih sistema",
		"siforgjed" => 100010,
		"upisanostud" => 45,
		"brojsatitjedno" => NULL,
	),
	array(
		"kratpred" => "EKONEN",
		"nazpred" => "Ekonomika u energetici",
		"siforgjed" => 100005,
		"upisanostud" => 21,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ELSTR1",
		"nazpred" => "Električki strojevi I",
		"siforgjed" => 100004,
		"upisanostud" => 1,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ELIZNA",
		"nazpred" => "Elektronički izvori napajanja",
		"siforgjed" => 100010,
		"upisanostud" => 5,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "ELKOS",
		"nazpred" => "Elektronički komutacijski sistemi",
		"siforgjed" => 100010,
		"upisanostud" => 10,
		"brojsatitjedno" => 4,
	),
	array(
		"kratpred" => "EEL-IP",
		"nazpred" => "Energetska elektronika-izabrana poglavlja",
		"siforgjed" => 100005,
		"upisanostud" => 110,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "EEL",
		"nazpred" => "Energetska elektronika",
		"siforgjed" => 100005,
		"upisanostud" => 1,
		"brojsatitjedno" => NULL,
	),
	array(
		"kratpred" => "FLASER",
		"nazpred" => "Fizika lasera",
		"siforgjed" => 100001,
		"upisanostud" => 2,
		"brojsatitjedno" => 1,
	),
	array(
		"kratpred" => "FOSE",
		"nazpred" => "Fizikalne osnove spremanja energije",
		"siforgjed" => 100001,
		"upisanostud" => 70,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "OPES",
		"nazpred" => "Optimalni pogon elektroenergetskog sustava",
		"siforgjed" => 100005,
		"upisanostud" => 1,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "OETEM",
		"nazpred" => "Organizacija i eksploatacija telekomunikacijske mreže",
		"siforgjed" => 100006,
		"upisanostud" => 2,
		"brojsatitjedno" => NULL,
	),
	array(
		"kratpred" => "ORAKOM",
		"nazpred" => "Osnove radiokomunikacija",
		"siforgjed" => 100011,
		"upisanostud" => 8,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "OELAK",
		"nazpred" => "Osnove elektroakustike",
		"siforgjed" => 100009,
		"upisanostud" => 0,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "PIESS",
		"nazpred" => "Projektiranje integriranih elektroničkih sklopova",
		"siforgjed" => 100010,
		"upisanostud" => 0,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "PIP",
		"nazpred" => "Projektiranje industrijskih postrojenja",
		"siforgjed" => 100004,
		"upisanostud" => 0,
		"brojsatitjedno" => NULL,
	),
	array(
		"kratpred" => "ZPM06A2",
		"nazpred" => "Projektiranje programske podrške",
		"siforgjed" => 100002,
		"upisanostud" => 1,
		"brojsatitjedno" => 4,
	),
	array(
		"kratpred" => "PROTEM",
		"nazpred" => "Projektiranje telekomunikacijskih mreža",
		"siforgjed" => 100006,
		"upisanostud" => 18,
		"brojsatitjedno" => 1,
	),
	array(
		"kratpred" => "RAKOM",
		"nazpred" => "Radiokomunikacije",
		"siforgjed" => 100011,
		"upisanostud" => 1,
		"brojsatitjedno" => NULL,
	),
	array(
		"kratpred" => "RESE",
		"nazpred" => "Regulacija električkih strojeva u elektranama",
		"siforgjed" => 100004,
		"upisanostud" => 1,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "STAEES",
		"nazpred" => "Stabilnost elektroenergetskih sistema",
		"siforgjed" => 100005,
		"upisanostud" => 2,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "UNUF",
		"nazpred" => "Uvod u nuklearnu fiziku",
		"siforgjed" => 100001,
		"upisanostud" => 14,
		"brojsatitjedno" => 4,
	),
	array(
		"kratpred" => "OSKLOP",
		"nazpred" => "Osnovni elektronički sklopovi",
		"siforgjed" => 100010,
		"upisanostud" => 0,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "TEMRE",
		"nazpred" => "Telekomunikacijske mreže",
		"siforgjed" => 100006,
		"upisanostud" => 0,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ELENS",
		"nazpred" => "Elektroenergetski sistem",
		"siforgjed" => 100005,
		"upisanostud" => 10,
		"brojsatitjedno" => NULL,
	),
	array(
		"kratpred" => "OEEN",
		"nazpred" => "Osnove elektroenergetike",
		"siforgjed" => 100005,
		"upisanostud" => 25,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "SISTR",
		"nazpred" => "Sinkroni strojevi",
		"siforgjed" => 100004,
		"upisanostud" => 1,
		"brojsatitjedno" => NULL,
	),
	array(
		"kratpred" => "PTEP",
		"nazpred" => "Prelaz topline u energ. postrojenjima",
		"siforgjed" => 100004,
		"upisanostud" => 2,
		"brojsatitjedno" => NULL,
	),
	array(
		"kratpred" => "ELSKLOP",
		"nazpred" => "Elektronički sklopovi",
		"siforgjed" => 100010,
		"upisanostud" => 10,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "EINKO",
		"nazpred" => "Elektronička instrumentacija i konstrukcije",
		"siforgjed" => 100010,
		"upisanostud" => 9,
		"brojsatitjedno" => 4,
	),
	array(
		"kratpred" => "ELMJE",
		"nazpred" => "Elektronička mjerenja i komponente",
		"siforgjed" => 100010,
		"upisanostud" => 0,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "ESIB",
		"nazpred" => "Energetski sistemi i bilance",
		"siforgjed" => 100005,
		"upisanostud" => 2,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "FIZ3",
		"nazpred" => "Fizika III",
		"siforgjed" => 100001,
		"upisanostud" => 0,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "NUMAT",
		"nazpred" => "Numerička matematika",
		"siforgjed" => 100002,
		"upisanostud" => 2,
		"brojsatitjedno" => 4,
	),
	array(
		"kratpred" => "OPEF",
		"nazpred" => "Odabrana poglavlja energetske fizike",
		"siforgjed" => 100001,
		"upisanostud" => 1,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "OPOMAT",
		"nazpred" => "Odabrana poglavlja matematike",
		"siforgjed" => 100002,
		"upisanostud" => 25,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "OES",
		"nazpred" => "Osnove električkih strojeva",
		"siforgjed" => 100004,
		"upisanostud" => 0,
		"brojsatitjedno" => NULL,
	),
	array(
		"kratpred" => "STOMAT",
		"nazpred" => "Stohastička matematika",
		"siforgjed" => 100002,
		"upisanostud" => 20,
		"brojsatitjedno" => 1,
	),
	array(
		"kratpred" => "ELRAČ",
		"nazpred" => "Elektronička računala",
		"siforgjed" => 100010,
		"upisanostud" => 32,
		"brojsatitjedno" => NULL,
	),
	array(
		"kratpred" => "ELEL1",
		"nazpred" => "Elektronički elementi",
		"siforgjed" => 100010,
		"upisanostud" => 21,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ZFI01O1",
		"nazpred" => "Fizika I",
		"siforgjed" => 100001,
		"upisanostud" => 70,
		"brojsatitjedno" => 4,
	),
	array(
		"kratpred" => "ZFI02O2",
		"nazpred" => "Fizika II",
		"siforgjed" => 100001,
		"upisanostud" => 2,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "FOE",
		"nazpred" => "Fizikalne osnove elektrotehnike",
		"siforgjed" => 100003,
		"upisanostud" => 0,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "OE",
		"nazpred" => "Osnove elektrotehnike",
		"siforgjed" => 100003,
		"upisanostud" => 2,
		"brojsatitjedno" => NULL,
	),
	array(
		"kratpred" => "TEOREL",
		"nazpred" => "Teoretska elektrotehnika",
		"siforgjed" => 100003,
		"upisanostud" => 1,
		"brojsatitjedno" => 1,
	),
	array(
		"kratpred" => "EENMR3",
		"nazpred" => "Elektroenergetske mreže III",
		"siforgjed" => 100005,
		"upisanostud" => 5,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "EENMR1",
		"nazpred" => "Elektroenergetske mreže I",
		"siforgjed" => 100005,
		"upisanostud" => 5,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ELSKLOP",
		"nazpred" => "Elektronički sklopovi",
		"siforgjed" => 100010,
		"upisanostud" => 10,
		"brojsatitjedno" => 4,
	),
	array(
		"kratpred" => "RADAR",
		"nazpred" => "Radari i radiokomunikacije",
		"siforgjed" => 100011,
		"upisanostud" => 2,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "RALOTE",
		"nazpred" => "Radiolokacija i radiotelemetrija",
		"siforgjed" => 100011,
		"upisanostud" => 13,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "INE03O6",
		"nazpred" => "Elektronička instrumentacija",
		"siforgjed" => 100010,
		"upisanostud" => 15,
		"brojsatitjedno" => 1,
	),
	array(
		"kratpred" => "EPROC",
		"nazpred" => "Energetski procesi",
		"siforgjed" => 100005,
		"upisanostud" => 2,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "MAT1",
		"nazpred" => "Matematika I",
		"siforgjed" => 100002,
		"upisanostud" => 6,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "MAT2",
		"nazpred" => "Matematika II",
		"siforgjed" => 100002,
		"upisanostud" => 6,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "MAT3",
		"nazpred" => "Matematika III",
		"siforgjed" => 100002,
		"upisanostud" => 17,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ISKLOP",
		"nazpred" => "Integrirani elektronički sklopovi",
		"siforgjed" => 100010,
		"upisanostud" => 0,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "UNUF",
		"nazpred" => "Uvod u nuklearnu fiziku",
		"siforgjed" => 100001,
		"upisanostud" => 13,
		"brojsatitjedno" => NULL,
	),
	array(
		"kratpred" => "NEP-K",
		"nazpred" => "Nuklearna energetska postrojenja - konstrukcijske vježbe",
		"siforgjed" => 100004,
		"upisanostud" => 0,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ZPM01O1",
		"nazpred" => "Linearna algebra",
		"siforgjed" => 100002,
		"upisanostud" => 110,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "ZPM02O1",
		"nazpred" => "Matematička analiza I",
		"siforgjed" => 100002,
		"upisanostud" => 70,
		"brojsatitjedno" => NULL,
	),
	array(
		"kratpred" => "ZOM01O1",
		"nazpred" => "Osnove elektrotehnike I",
		"siforgjed" => 100003,
		"upisanostud" => 1,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ZPM03O1",
		"nazpred" => "Primjena računala",
		"siforgjed" => 100002,
		"upisanostud" => 17,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "ZPM04O2",
		"nazpred" => "Matematička analiza II",
		"siforgjed" => 100002,
		"upisanostud" => 0,
		"brojsatitjedno" => 4,
	),
	array(
		"kratpred" => "ZOM02O2",
		"nazpred" => "Osnove elektrotehnike II",
		"siforgjed" => 100003,
		"upisanostud" => 3,
		"brojsatitjedno" => NULL,
	),
	array(
		"kratpred" => "ZPM2002",
		"nazpred" => "Programiranje",
		"siforgjed" => 100002,
		"upisanostud" => 15,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ZPM06O3",
		"nazpred" => "Matematička analiza III",
		"siforgjed" => 100002,
		"upisanostud" => 1,
		"brojsatitjedno" => 1,
	),
	array(
		"kratpred" => "ZOM03O3",
		"nazpred" => "Mjerenja u elektrotehnici",
		"siforgjed" => 100003,
		"upisanostud" => 2,
		"brojsatitjedno" => NULL,
	),
	array(
		"kratpred" => "ZSE01O3",
		"nazpred" => "Energetska elektrotehnika",
		"siforgjed" => 100003,
		"upisanostud" => 0,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ZER3001",
		"nazpred" => "Elektronički elementi",
		"siforgjed" => 100010,
		"upisanostud" => 0,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "ZPM07O3",
		"nazpred" => "Algoritmi i strukture podataka",
		"siforgjed" => 100002,
		"upisanostud" => 5,
		"brojsatitjedno" => 4,
	),
	array(
		"kratpred" => "ZPM4001",
		"nazpred" => "Stohastička i numerička matematika",
		"siforgjed" => 100002,
		"upisanostud" => 13,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ZPM4002",
		"nazpred" => "Diskretna i stohastička matematika",
		"siforgjed" => 100002,
		"upisanostud" => 20,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ZOM03O4",
		"nazpred" => "Mjerenja u elektrotehnici-praktikum",
		"siforgjed" => 100003,
		"upisanostud" => 0,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "ZRS01O4",
		"nazpred" => "Osnove digitalnih računala",
		"siforgjed" => 100008,
		"upisanostud" => 0,
		"brojsatitjedno" => NULL,
	),
	array(
		"kratpred" => "ZER4002",
		"nazpred" => "Elektronički sklopovi",
		"siforgjed" => 100010,
		"upisanostud" => 40,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ZFI03O5",
		"nazpred" => "Fizika materijala",
		"siforgjed" => 100001,
		"upisanostud" => 45,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "AUT6003",
		"nazpred" => "Elektronička instrumentacija i mjerenja",
		"siforgjed" => 100010,
		"upisanostud" => 17,
		"brojsatitjedno" => 4,
	),
	array(
		"kratpred" => "ZER15A2",
		"nazpred" => "Složeni elektronički sklopovi",
		"siforgjed" => 100010,
		"upisanostud" => 8,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ENE04O6",
		"nazpred" => "Osnove energetske elektronike",
		"siforgjed" => 100005,
		"upisanostud" => 18,
		"brojsatitjedno" => 1,
	),
	array(
		"kratpred" => "ZRS11A2",
		"nazpred" => "Analiza osjetljivosti, sinteza i optimiranje sustava",
		"siforgjed" => 100008,
		"upisanostud" => 0,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "ZRS17A2",
		"nazpred" => "Procesna mjerenja",
		"siforgjed" => 100008,
		"upisanostud" => 0,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ZRS12A2",
		"nazpred" => "Otvoreno računarstvo",
		"siforgjed" => 100008,
		"upisanostud" => 0,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "ZPM05A2",
		"nazpred" => "Matematičke osnove optimalnog upravljanja",
		"siforgjed" => 100002,
		"upisanostud" => 25,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ENE02O5",
		"nazpred" => "Električni strojevi i transformatori",
		"siforgjed" => 100004,
		"upisanostud" => 0,
		"brojsatitjedno" => 4,
	),
	array(
		"kratpred" => "ZOM04O5",
		"nazpred" => "Teorijska elektrotehnika",
		"siforgjed" => 100003,
		"upisanostud" => 1,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ESA07O6",
		"nazpred" => "Osnove čvrstoće i konstruiranja",
		"siforgjed" => 100004,
		"upisanostud" => 2,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ESA5001",
		"nazpred" => "Osnove električnih strojeva i transformatora",
		"siforgjed" => 100004,
		"upisanostud" => 0,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ESA02O5",
		"nazpred" => "Energetska elektronika",
		"siforgjed" => 100004,
		"upisanostud" => 2,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ESA03O5",
		"nazpred" => "Elektrotehnički materijali i tehnologija",
		"siforgjed" => 100004,
		"upisanostud" => 110,
		"brojsatitjedno" => 4,
	),
	array(
		"kratpred" => "ESA6002",
		"nazpred" => "Kolektorski i elektronički komutirani motori",
		"siforgjed" => 100004,
		"upisanostud" => 1,
		"brojsatitjedno" => NULL,
	),
	array(
		"kratpred" => "INE01O5",
		"nazpred" => "Elektronička mjerenja i komponente",
		"siforgjed" => 100010,
		"upisanostud" => 2,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "RKP03O5",
		"nazpred" => "Elektroakustika",
		"siforgjed" => 100009,
		"upisanostud" => 0,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "RKP09O7",
		"nazpred" => "Optoelektronički sklopovi",
		"siforgjed" => 100010,
		"upisanostud" => 70,
		"brojsatitjedno" => 4,
	),
	array(
		"kratpred" => "TKI03O5",
		"nazpred" => "Telekomunikacijske mreže",
		"siforgjed" => 100006,
		"upisanostud" => 0,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ZPM11O5",
		"nazpred" => "Programske paradigme i jezici",
		"siforgjed" => 100002,
		"upisanostud" => 2,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "ZPM02A1",
		"nazpred" => "Operacijska istraživanja",
		"siforgjed" => 100002,
		"upisanostud" => 10,
		"brojsatitjedno" => 1,
	),
	array(
		"kratpred" => "ENE6101",
		"nazpred" => "Energetski izvori",
		"siforgjed" => 100005,
		"upisanostud" => 9,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "IRB01A1",
		"nazpred" => "Fizika poluvodiča",
		"siforgjed" => 100001,
		"upisanostud" => 11,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ZPM01A1",
		"nazpred" => "Stohastički procesi",
		"siforgjed" => 100002,
		"upisanostud" => 70,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ZPM09O4",
		"nazpred" => "Numerička matematika",
		"siforgjed" => 100002,
		"upisanostud" => 8,
		"brojsatitjedno" => NULL,
	),
	array(
		"kratpred" => "AUT5002",
		"nazpred" => "Elektronička računala",
		"siforgjed" => 100010,
		"upisanostud" => 3,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ZPM08O4",
		"nazpred" => "Stohastička matematika",
		"siforgjed" => 100002,
		"upisanostud" => 18,
		"brojsatitjedno" => 1,
	),
	array(
		"kratpred" => "ZPM10O4",
		"nazpred" => "Diskretna matematika",
		"siforgjed" => 100002,
		"upisanostud" => 17,
		"brojsatitjedno" => 4,
	),
	array(
		"kratpred" => "ENE01O5",
		"nazpred" => "Energetski procesi",
		"siforgjed" => 100005,
		"upisanostud" => 11,
		"brojsatitjedno" => NULL,
	),
	array(
		"kratpred" => "ENE08O7",
		"nazpred" => "Elektroenergetske mreže",
		"siforgjed" => 100005,
		"upisanostud" => 0,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ENE09O7",
		"nazpred" => "Numerička analiza elektroenergetskog sustava",
		"siforgjed" => 100005,
		"upisanostud" => 2,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "ENE14O8",
		"nazpred" => "Zaštita i automatika elektroenergetskog sustava",
		"siforgjed" => 100005,
		"upisanostud" => 5,
		"brojsatitjedno" => NULL,
	),
	array(
		"kratpred" => "ENE15O8",
		"nazpred" => "Energetika i okoliš",
		"siforgjed" => 100005,
		"upisanostud" => 9,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ESA04O6",
		"nazpred" => "Regulacijska tehnika",
		"siforgjed" => 100004,
		"upisanostud" => 2,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "ESA10O7",
		"nazpred" => "Elektromotorni pogoni",
		"siforgjed" => 100004,
		"upisanostud" => 0,
		"brojsatitjedno" => 4,
	),
	array(
		"kratpred" => "ESA11O7",
		"nazpred" => "Upravljanje elektromotornim pogonima",
		"siforgjed" => 100004,
		"upisanostud" => 0,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ESA13O8",
		"nazpred" => "Projektiranje industrijskih postrojenja",
		"siforgjed" => 100004,
		"upisanostud" => 0,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ESA14O7",
		"nazpred" => "Razvod električne energije",
		"siforgjed" => 100004,
		"upisanostud" => 1,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "ESA16O9",
		"nazpred" => "Mehatronički sustavi",
		"siforgjed" => 100004,
		"upisanostud" => 2,
		"brojsatitjedno" => NULL,
	),
	array(
		"kratpred" => "AUT06O6",
		"nazpred" => "Elektronička mjerenja i instrumentacija",
		"siforgjed" => 100010,
		"upisanostud" => 12,
		"brojsatitjedno" => 1,
	),
	array(
		"kratpred" => "INE08O7",
		"nazpred" => "Mikroelektronički sklopovi",
		"siforgjed" => 100010,
		"upisanostud" => 0,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "RKP08O7",
		"nazpred" => "Osnove radiokomunikacijskih sustava",
		"siforgjed" => 100011,
		"upisanostud" => 6,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "RKP10O7",
		"nazpred" => "Elektroakustički signali i sustavi",
		"siforgjed" => 100009,
		"upisanostud" => 0,
		"brojsatitjedno" => 4,
	),
	array(
		"kratpred" => "TKI11O8",
		"nazpred" => "Pouzdanost telekomunikacijskih sustava",
		"siforgjed" => 100006,
		"upisanostud" => 1,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ZER07A1",
		"nazpred" => "Osnove mikroelektroničkih sklopova",
		"siforgjed" => 100010,
		"upisanostud" => 2,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ZFI03A2",
		"nazpred" => "Fizika lasera",
		"siforgjed" => 100001,
		"upisanostud" => 0,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "ZVF01A1",
		"nazpred" => "Radiolokacija i navigacija",
		"siforgjed" => 100011,
		"upisanostud" => 10,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ZEA01A1",
		"nazpred" => "Ultrazvuk i hidroakustika",
		"siforgjed" => 100009,
		"upisanostud" => 70,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "ZPM03A1",
		"nazpred" => "Projektiranje informacijskih sustava",
		"siforgjed" => 100002,
		"upisanostud" => 10,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "ZRS16A2",
		"nazpred" => "Upravljanje, slijedni sustavi i senzori u robotici",
		"siforgjed" => 100008,
		"upisanostud" => 3,
		"brojsatitjedno" => NULL,
	),
	array(
		"kratpred" => "FSB13A2",
		"nazpred" => "Regulacija u energetskim postrojenjima",
		"siforgjed" => 100004,
		"upisanostud" => 0,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ZES15A1",
		"nazpred" => "Sklopni i zaštitni uređaji u postrojenjima",
		"siforgjed" => 100004,
		"upisanostud" => 1,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "ZES12A2",
		"nazpred" => "Projektiranje i konstruiranje u elektrostrojarstvu",
		"siforgjed" => 100004,
		"upisanostud" => 2,
		"brojsatitjedno" => 4,
	),
	array(
		"kratpred" => "ZEN01A1",
		"nazpred" => "Pouzdanost elektroenergetskog sustava",
		"siforgjed" => 100005,
		"upisanostud" => 5,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "IHP10A2",
		"nazpred" => "Energetski izvori",
		"siforgjed" => 100005,
		"upisanostud" => 3,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ZEN04A1",
		"nazpred" => "Ekonomika u energetici",
		"siforgjed" => 100005,
		"upisanostud" => 0,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "ZEN03A1",
		"nazpred" => "Numerički postupci u elektroenergetici",
		"siforgjed" => 100005,
		"upisanostud" => 5,
		"brojsatitjedno" => 1,
	),
	array(
		"kratpred" => "ESA02O5",
		"nazpred" => "Energetska elektronika",
		"siforgjed" => 100004,
		"upisanostud" => 18,
		"brojsatitjedno" => 1,
	),
	array(
		"kratpred" => "ZEN09B1",
		"nazpred" => "Dinamika elektroenergetskog sustava",
		"siforgjed" => 100005,
		"upisanostud" => 8,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ZRS01A1",
		"nazpred" => "Adaptivno i robusno upravljanje",
		"siforgjed" => 100008,
		"upisanostud" => 0,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "ZPM04B1",
		"nazpred" => "Objektno orijentirano programiranje",
		"siforgjed" => 100002,
		"upisanostud" => 21,
		"brojsatitjedno" => 4,
	),
	array(
		"kratpred" => "ZRS05B1",
		"nazpred" => "Inteligentno upravljanje sustavima",
		"siforgjed" => 100008,
		"upisanostud" => 0,
		"brojsatitjedno" => 4,
	),
	array(
		"kratpred" => "ZRS09B1",
		"nazpred" => "Identifikacija procesa",
		"siforgjed" => 100008,
		"upisanostud" => 70,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ZRS06B1",
		"nazpred" => "Automatizacija brodskih procesa",
		"siforgjed" => 100008,
		"upisanostud" => 1,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ZES09B1",
		"nazpred" => "Elektronički pretvarači za elektromotorne pogone",
		"siforgjed" => 100010,
		"upisanostud" => 23,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "ESA15O8",
		"nazpred" => "Automatizirana ispitivanja elektrotehničkih uređaja",
		"siforgjed" => 100004,
		"upisanostud" => 0,
		"brojsatitjedno" => NULL,
	),
	array(
		"kratpred" => "ZRS02A1",
		"nazpred" => "Alarmni sustavi",
		"siforgjed" => 100008,
		"upisanostud" => 5,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ZES16A1",
		"nazpred" => "Sinkroni strojevi i uzbude",
		"siforgjed" => 100004,
		"upisanostud" => 0,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "ZRS07B1",
		"nazpred" => "Odabrana poglavlja iz programskog inženjerstva",
		"siforgjed" => 100008,
		"upisanostud" => 1,
		"brojsatitjedno" => NULL,
	),
	array(
		"kratpred" => "ZVF11B1",
		"nazpred" => "Projektiranje radiofrekvencijskih pojačala",
		"siforgjed" => 100011,
		"upisanostud" => 20,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "ZVF04A1",
		"nazpred" => "Numerički postupci u radiokomunikacijama",
		"siforgjed" => 100011,
		"upisanostud" => 23,
		"brojsatitjedno" => 1,
	),
	array(
		"kratpred" => "ZRS10B1",
		"nazpred" => "Vođenje projekata automatike",
		"siforgjed" => 100008,
		"upisanostud" => 0,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "ZRS03B1",
		"nazpred" => "Vođenje i upravljanje plovila",
		"siforgjed" => 100008,
		"upisanostud" => 1,
		"brojsatitjedno" => 4,
	),
	array(
		"kratpred" => "ZRS08B1",
		"nazpred" => "Realizacija upravljačkih algoritama i računalnih arhitektura",
		"siforgjed" => 100008,
		"upisanostud" => 0,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ZVF09B1",
		"nazpred" => "Tehnologija radiofrekvencijskih komponenata",
		"siforgjed" => 100011,
		"upisanostud" => 0,
		"brojsatitjedno" => NULL,
	),
	array(
		"kratpred" => "TKI05B1",
		"nazpred" => "Razvoj telekomunikacijske programske podrške",
		"siforgjed" => 100006,
		"upisanostud" => 1,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "TKI08B1",
		"nazpred" => "Organizacija telekomunikacijske mreže",
		"siforgjed" => 100006,
		"upisanostud" => 2,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "TKI09B1",
		"nazpred" => "Informacijski sustav telekmunikacijske mreže",
		"siforgjed" => 100006,
		"upisanostud" => 0,
		"brojsatitjedno" => 4,
	),
	array(
		"kratpred" => "ZVF05A1",
		"nazpred" => "Radiotelemetrija",
		"siforgjed" => 100011,
		"upisanostud" => 0,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ZEA03A1",
		"nazpred" => "Psihoakustika",
		"siforgjed" => 100009,
		"upisanostud" => 1,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "ZEA05A1",
		"nazpred" => "Govorna i glazbena akustika",
		"siforgjed" => 100009,
		"upisanostud" => 2,
		"brojsatitjedno" => NULL,
	),
	array(
		"kratpred" => "ESA17O6",
		"nazpred" => "Električni strojevi",
		"siforgjed" => 100004,
		"upisanostud" => 70,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ESA01O5",
		"nazpred" => "Elektromehanička i elektromagnetska pretvorba",
		"siforgjed" => 100004,
		"upisanostud" => 0,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "ESA19O8",
		"nazpred" => "Razvoj elektrotehničkih proizvoda",
		"siforgjed" => 100004,
		"upisanostud" => 5,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ZPM06A2",
		"nazpred" => "Projektiranje programske podrške",
		"siforgjed" => 100002,
		"upisanostud" => 29,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ZPM05O2",
		"nazpred" => "Programiranje",
		"siforgjed" => 100002,
		"upisanostud" => 17,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ZRS16A2",
		"nazpred" => "Fleksibilni proizvodni sustavi",
		"siforgjed" => 100008,
		"upisanostud" => 18,
		"brojsatitjedno" => 1,
	),
	array(
		"kratpred" => "ZRS08B1",
		"nazpred" => "Realizacija algoritama i računalnih arhitektura",
		"siforgjed" => 100008,
		"upisanostud" => 1,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "Z0M03O3",
		"nazpred" => "Mjerenja u elektrotehnici",
		"siforgjed" => 100003,
		"upisanostud" => 2,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ZPM06A2",
		"nazpred" => "Ergonomija računalne i programske opreme",
		"siforgjed" => 100002,
		"upisanostud" => 0,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "ZRS09B1",
		"nazpred" => "Identifikacija procesa",
		"siforgjed" => 100008,
		"upisanostud" => 70,
		"brojsatitjedno" => NULL,
	),
	array(
		"kratpred" => "ZPM07A1",
		"nazpred" => "Osnove baza podataka",
		"siforgjed" => 100002,
		"upisanostud" => 15,
		"brojsatitjedno" => 2,
	),
	array(
		"kratpred" => "ENE15O8",
		"nazpred" => "Energetika i okoliš",
		"siforgjed" => 100005,
		"upisanostud" => 1,
		"brojsatitjedno" => 3,
	),
	array(
		"kratpred" => "ZOM03O3",
		"nazpred" => "Mjerenja u elektrotehnici",
		"siforgjed" => 100003,
		"upisanostud" => 2,
		"brojsatitjedno" => 4,
	),
);


}
